# Generated by Django 3.2.13 on 2022-06-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_hospital',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
